### YamlMime:ManagedReference
items:
- uid: WebApplication1
  commentId: N:WebApplication1
  id: WebApplication1
  children:
  - WebApplication1.Program
  langs:
  - csharp
  - vb
  name: WebApplication1
  nameWithType: WebApplication1
  fullName: WebApplication1
  type: Namespace
  assemblies:
  - WebApplication1
references:
- uid: WebApplication1.Program
  commentId: T:WebApplication1.Program
  href: WebApplication1.Program.html
  name: Program
  nameWithType: Program
  fullName: WebApplication1.Program
