name: .Net

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Debugland/**'
      - '.github/workflows/**'

permissions:
  checks: write
  contents: read
  pull-requests: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout code   
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Angiv din .NET-version her
    
    - name: Restore dependencies
      run: dotnet restore ./Debugland/Debugland.sln

    - name: Build
      run: dotnet build ./Debugland/Debugland.sln --configuration Release --no-restore
    
      
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Angiv din .NET-version her
    
    - name: Install ctrf
      run: npm install github-actions-ctrf@0.0.29
   
    - name: Dotnet Manifesto
      run: dotnet new tool-manifest
      
    - name: Install DotnetCTRFreporter
      run: dotnet tool install DotnetCtrfJsonReporter --local
      
    - name: Test
      run: dotnet test ./Debugland/TestProject/Testproject.csproj --logger "trx;logfilename=testResults.trx"
    
    
    - name: convert Report
      run: dotnet tool run DotnetCtrfJsonReporter -p "/home/runner/work/Vita/Vita/Vita_WebAPI/Vita_Test/TestResults/testResults.trx"
    
    - name: Publish Test Summary Results
      run: npx github-actions-ctrf ./ctrf/ctrf-report.json --pr-comment
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
